name: Update News Articles

on:
  schedule:
    - cron: "0 6,18 * * *"  # Run at 6 AM and 6 PM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run main.py (fetch and process articles)
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          DBNAME: ${{ secrets.DBNAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py
